services:
  logs-db:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - logs-db:/var/lib/postgresql/data

  logs-service:
    build: .
    env_file:
      - .env.docker
    ports:
      - "4002:4002"

volumes:
  logs-db:

